version: '3.3'

services:
  db:
    image: mysql:8.0
    #restart: always
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
        #    volumes:
        #      - ./.docker/mysql:/var/lib/mysql
